SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM reporte_mensual;
DELETE FROM reporte_parcial_y_final;
DELETE FROM reporte_actividad;
DELETE FROM reporte_entregable;
DELETE FROM observacion_reporte;
DELETE FROM reporte;
DELETE FROM autoevaluacion;
DELETE FROM evaluacion_ov;
DELETE FROM formato_inicial;
DELETE FROM prorroga;
DELETE FROM actividad_practicante;
DELETE FROM actividad;
DELETE FROM asignacion;
DELETE FROM solicitud_proyecto;
DELETE FROM solicitud;
DELETE FROM practica;
DELETE FROM proyecto;
DELETE FROM tecnico_responsable;
DELETE FROM organizacion_vinculada;
DELETE FROM practicante;
DELETE FROM profesor;
DELETE FROM coordinador;
DELETE FROM administrador;
DELETE FROM experiencia_educativa;
DELETE FROM usuario_rol;
DELETE FROM usuario;

ALTER TABLE usuario AUTO_INCREMENT = 1;
ALTER TABLE organizacion_vinculada AUTO_INCREMENT = 1;
ALTER TABLE tecnico_responsable AUTO_INCREMENT = 1;
ALTER TABLE proyecto AUTO_INCREMENT = 1;
ALTER TABLE practica AUTO_INCREMENT = 1;
ALTER TABLE actividad AUTO_INCREMENT = 1;
ALTER TABLE actividad_practicante AUTO_INCREMENT = 1;
ALTER TABLE solicitud AUTO_INCREMENT = 1;
ALTER TABLE solicitud_proyecto AUTO_INCREMENT = 1;
ALTER TABLE asignacion AUTO_INCREMENT = 1;
ALTER TABLE reporte AUTO_INCREMENT = 1;
ALTER TABLE reporte_actividad AUTO_INCREMENT = 1;
ALTER TABLE reporte_entregable AUTO_INCREMENT = 1;
ALTER TABLE observacion_reporte AUTO_INCREMENT = 1;
ALTER TABLE autoevaluacion AUTO_INCREMENT = 1;
ALTER TABLE evaluacion_ov AUTO_INCREMENT = 1;
ALTER TABLE formato_inicial AUTO_INCREMENT = 1;
ALTER TABLE prorroga AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
